# write ansible playbook here

---
- name: configure all nodes
  hosts: all
  remote_user: root

  roles:
    - base

- name: configure webservers
  hosts: webservers
  remote_user: root

  roles:
    - webservers